/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TravellerIDInterface extends Interface {
  getFunction(nameOrSignature: "createId" | "getRecord"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "IdCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createId",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getRecord", values: [string]): string;

  decodeFunctionResult(functionFragment: "createId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
}

export namespace IdCreatedEvent {
  export type InputTuple = [
    blockchainId: string,
    profileHash: BytesLike,
    issuer: AddressLike
  ];
  export type OutputTuple = [
    blockchainId: string,
    profileHash: string,
    issuer: string
  ];
  export interface OutputObject {
    blockchainId: string;
    profileHash: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TravellerID extends BaseContract {
  connect(runner?: ContractRunner | null): TravellerID;
  waitForDeployment(): Promise<this>;

  interface: TravellerIDInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createId: TypedContractMethod<
    [blockchainId: string, profileHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getRecord: TypedContractMethod<
    [blockchainId: string],
    [[string, bigint, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createId"
  ): TypedContractMethod<
    [blockchainId: string, profileHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [blockchainId: string],
    [[string, bigint, string]],
    "view"
  >;

  getEvent(
    key: "IdCreated"
  ): TypedContractEvent<
    IdCreatedEvent.InputTuple,
    IdCreatedEvent.OutputTuple,
    IdCreatedEvent.OutputObject
  >;

  filters: {
    "IdCreated(string,bytes32,address)": TypedContractEvent<
      IdCreatedEvent.InputTuple,
      IdCreatedEvent.OutputTuple,
      IdCreatedEvent.OutputObject
    >;
    IdCreated: TypedContractEvent<
      IdCreatedEvent.InputTuple,
      IdCreatedEvent.OutputTuple,
      IdCreatedEvent.OutputObject
    >;
  };
}
